function seedNeighborhood() {
  return {
    profile: {
      id: "me",
      name: "小赵",
      community: "梧桐里",
      credit: 96,
      avatarUrl: "",
    },
    users: [
      {
        id: "u-101",
        name: "王启明",
        role: "社区志愿者",
        building: "3栋",
        distance: 80,
        verified: ["实名", "活体", "同小区"],
        skills: ["代取快递", "小型搬运", "工具借还"],
        rating: 4.9,
        completed: 23,
        complaint: 0,
        avgResponse: 3,
        baseQuote: 10,
        credit: 96,
      },
      {
        id: "u-102",
        name: "林小禾",
        role: "物业认证服务者",
        building: "5栋",
        distance: 220,
        verified: ["实名", "同小区", "物业认证"],
        skills: ["代取快递", "工具借还"],
        rating: 4.8,
        completed: 41,
        complaint: 1,
        avgResponse: 6,
        baseQuote: 12,
        credit: 93,
      },
      {
        id: "u-103",
        name: "陈海",
        role: "社区达人",
        building: "1栋",
        distance: 410,
        verified: ["实名", "同小区"],
        skills: ["小型搬运", "工具借还"],
        rating: 4.7,
        completed: 17,
        complaint: 0,
        avgResponse: 9,
        baseQuote: 16,
        credit: 90,
      },
      {
        id: "u-104",
        name: "周南",
        role: "机构认证服务者",
        building: "社区服务站",
        distance: 680,
        verified: ["实名", "活体", "机构认证"],
        skills: ["陪诊调度", "关怀调度"],
        rating: 4.9,
        completed: 36,
        complaint: 0,
        avgResponse: 8,
        baseQuote: 100,
        credit: 98,
      },
    ],
    tools: [
      {
        id: "tool-1",
        name: "小推车",
        owner: "3栋管家",
        building: "3栋大堂",
        availability: "全天可借",
        price: 0,
        priceText: "2小时内免费",
        deposit: "逾期需要登记",
        status: "可借",
        icon: "cart",
      },
      {
        id: "tool-2",
        name: "折叠梯",
        owner: "林小禾",
        building: "5栋",
        availability: "明天 9:00 后",
        price: 5,
        priceText: "5元/次",
        deposit: "需实名确认",
        status: "需确认",
        icon: "ladder",
      },
      {
        id: "tool-3",
        name: "工具箱",
        owner: "物业维修间",
        building: "物业中心",
        availability: "工作日 9:00-18:00",
        price: 0,
        priceText: "免费",
        deposit: "物业见证取还",
        status: "可借",
        icon: "box",
      },
    ],
    feed: [
      {
        id: "p-1",
        name: "小鱼丸",
        time: "2分钟前",
        text: "今天在小区花园发现一只超可爱的小猫，晒太阳晒得很认真。",
        meta: "梧桐里花园",
        tag: "日常发现",
        visual: "pet",
      },
      {
        id: "p-2",
        name: "阿树",
        time: "1小时前",
        text: "周六想组队去河堤散步，路线轻松，已经有 3 人报名。",
        meta: "3人已报名",
        tag: "周末活动",
        visual: null,
      },
      {
        id: "p-3",
        name: "安安",
        time: "3小时前",
        text: "楼下新开的咖啡角很安静，推荐给大家，适合等人和取还小物。",
        meta: "北门 60 米",
        tag: "附近推荐",
        visual: "coffee",
      },
    ],
    orders: [],
  };
}

module.exports = { seedNeighborhood };
